### ISSUE TITLE
Install successful. Unable to access pi-hole web interface

### ISSUE THREAD

**Issue by whisperdancer** [rodeodomino/algo-pihole#18]
AWS Lightsail install:

Great job on this! Thank you for your efforts. My install was successful. However, try as I may, I can't figure out how to connect to pi-hole web interface. I did ssh into the server and confirmed pi-hole is running. I tried the following:

Not connected to tunnel:
http://<private-ip>/admin times out
http://<public-ip>/admin times out as I would expect

Connected to tunnel:
http://<private-ip>/admin times out
http://<public-ip>/admin times out as I would expect

How can I access the pi-hole web ui? Thank you!

**Comment by whisperdancer** [comment]
Apparently it took out the brackets. The urs's are 
http://publicip/admin and http://privateip/admin

tried both off tunnel and in tunnel. Unable to access the pihole web interface.

**Comment by whisperdancer** [comment]
checked firewall and port 80 http is open on the server

**Comment by rodeodomino** [comment]
Have you tried [http://pi.hole/admin/](http://pi.hole/admin/)? Otherwise, the address that should be used is in `/etc/pihole/local.list` and you should see a line that says:

`[private-ip] pi.hole`

That address should work as well.

other than that, I'm not sure which settings/options/what not you're using to be able to troubleshoot further. I've tried reinstalling today and it worked fine.

**Comment by whisperdancer** [comment]
Hi, thank you for your quick response. I tried the url you suggested http://pi.hole/admin/ and I see the pihole web interface! Thank you!
